#!/usr/bin/env bash

: ${FMWK_JAR_DIR:=<abs path to>/target/MiniFramework-0.0.1-SNAPSHOT-jar-with-dependencies.jar}
: ${MESOS_LIB_PATH:=<path_to_native_mesos_library>}
: ${FMWK_EXECUTOR_LOG:=<path_to_dir_for_logging>}

exec java -cp ${FMWK_JAR_DIR}/MiniFramework-0.0.1-SNAPSHOT-jar-with-dependencies.jar \
 -Djava.library.path=${MESOS_LIB_DIR} \
  com.adsk.miniframework.MiniExecutor >> ${FWNK_EXECUTOR_LOG}/executor.log 2>&1
  